In [3]:
import numpy as np

# Rappels sur les tableaux :
# Création d'un tableau (rempli de 0) à deux dimensions : 10 et 3
tableau2N = np.zeros([10,3])

# Affichage du tableau
print(tableau2N)

# Affichage de la première dimension du tableau (10)
print(len(tableau2N))

# Affichage de la deuxième dimension du tableau (3)
print(len(tableau2N[0]))

# Création d'un tableau de nombres aléatoires, taille du tableau : 10x10
tableauRand = np.random.rand(10,10)
print(tableauRand)

# Création d'un tableau d'entiers aléatoires entre 0 et 10 (premier paramètre)
# taille du tableau : 10x3 
tableauRand2 = np.random.randint(10, size=(10,3))
print(tableauRand2)



[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
10
3
[[ 0.91692842  0.58516377  0.22964026  0.54044599  0.80764127  0.06610778
   0.06486364  0.90954586  0.44548449  0.07380947]
 [ 0.30613856  0.50340837  0.37400112  0.92147949  0.37719857  0.96097913
   0.28528696  0.05627136  0.47574077  0.36119593]
 [ 0.69965782  0.57931404  0.16693967  0.56188255  0.64703381  0.13584426
   0.0380564   0.52561116  0.11190063  0.33017561]
 [ 0.68375042  0.35899942  0.35237233  0.79909728  0.31102976  0.95492091
   0.10357009  0.31063965  0.05509086  0.73118992]
 [ 0.20273559  0.46938514  0.6524663   0.12602015  0.3966314   0.40308595
   0.05454863  0.5165485   0.1707513   0.20036436]
 [ 0.51703247  0.67865932  0.07424467  0.12273749  0.74548035  0.58479829
   0.33970538  0.20716206  0.0408255   0.22690684]
 [ 0.86947402  0.00143934  0.39684592  0.23640435  0.19193678  0.42939505
   0.15265379  0.583

In [4]:
#Pour les curieux qui demandent comment on fait une liste de listes : 
liste2N = []
liste = []
liste2N.append(liste)
print(liste2N)

[[]]


In [5]:
# Écrire l'algo de multiplication mais stocker les
# opérandes et le résultat dans un tableau
def multiplication(mult , tab):
    for i in range (len(tab)):
        tab[i][0]=i
        tab[i][1]=mult
        tab[i][2]=i*mult
tab=np.zeros([10,3])
multiplication(5,tab)
print(tab)
    

[[  0.   5.   0.]
 [  1.   5.   5.]
 [  2.   5.  10.]
 [  3.   5.  15.]
 [  4.   5.  20.]
 [  5.   5.  25.]
 [  6.   5.  30.]
 [  7.   5.  35.]
 [  8.   5.  40.]
 [  9.   5.  45.]]


In [6]:
# Exercice : soit un tableau à deux dimensions.
# Votre travail : triez d'abord chaque ligne par ordre croissant.
# Ensuite, triez les lignes (sans séparer les élémens) par ordre décroissant (de gauche à droite)
# Voici vos données d'entrées 

listeAtrier = [[1, 7, 3], [8, 4, 5], [6, 3, 1]]
tabAtrier = np.array(listeAtrier)
print(tabAtrier)

[[1 7 3]
 [8 4 5]
 [6 3 1]]


In [8]:
#Début de correction. Pour l'instant, triligne fonctionne 
def triligne (tab,a):
    for i in range (1, len(tab)):
        j=i
        while tab[a][j]<tab[a][j-1] and j>0:
            tab[a][j],tab[a][j-1]=tab[a][j-1],tab[a][j]
            j=j-1

def tritab (tab):
    for i in range (len(tab)):
        triligne(tab,i)

print(tabAtrier)
tritab(tabAtrier)
print(tabAtrier)

[[1 7 3]
 [8 4 5]
 [6 3 1]]
[[1 3 7]
 [4 5 8]
 [1 3 6]]


Exercice à faire par vous même : terminez l'exercice précédent en triant les lignes entre elles comme demandé dans l'énoncé. 