** Attention ** : le cours est à lire dans son intégralité pour le prochain TD. Si vous avez des questions, n'hésitez pas à les poser au prochain TD... car au TD suivant, vous aurez une interrogation !

In [5]:
import numpy as np
tableau = np.empty(20)
print(tableau)
print(tableau[1]==tableau[2])

tab2 = np.zeros(5)
print(tab2)
print(len(tableau) + len(tab2))

tab3 = np.array([1,2,5,6,7,10])
print(tab3)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.]
True
[ 0.  0.  0.  0.  0.]
25
[ 1  2  5  6  7 10]


**Les tableaux**

In [1]:
#Initialisation pour utiliser des "vrais" tableaux
import numpy as np
tableau = np.empty(10)
print(tableau)
print(len(tableau))
print(tableau[4])
autretableau = np.array([1,2,4,6,7])
print(autretableau)
print(autretableau[4])

[  1.08835389e-316   0.00000000e+000   6.90066334e-310   6.90069405e-310
   6.90068060e-310   6.90069405e-310   1.12638588e-316   0.00000000e+000
   6.90070023e-310   6.36598737e-311]
10
6.90068060163e-310
[1 2 4 6 7]
7


In [2]:
tableau0 = np.zeros(10)
print(tableau0)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


**Exercices ** 
1. Rechercher si un élément est présent dans un tableau. 
2. Vérifier que deux tableaux sont égaux. 
3. Vérifier qu'un tableau est le préfixe d'un autre. 
4. Rechercher le minimum d'un tableau.
5. Faire la somme des éléments d'un tableau.
6. Calculer la moyenne des éléments d'un tableau.
7. Multiplier tous les éléments d'un tableau par un facteur donné.
8. Décaler tous les éléments d'un tableau à droite.
9. Retourner un tableau contentant, case par case, le minimum de deux autres tableaux. 
10. Faire la somme des éléments dans les cases impaires d'un tableau. 

In [6]:
demo = np.array([1, 2, 3, 3, 5])
print(demo)

[1 2 3 3 5]


In [8]:
def plusUn(untableau):
    i = 0
    while i < len(untableau):
        untableau[i] = untableau[i]+1
        i += 1
    print("J'ai fini d'exécuter démo")

In [9]:
print(demo)
plusUn(demo)
print(demo)

[1 2 3 3 5]
J'ai fini d'exécuter démo
[2 3 4 4 6]


In [12]:
unevariable = 7 
def plusUn(a):
    a = a + 1
    print("J'ai fini d'exécuter plus un")

print(unevariable)
plusUn(unevariable)
print(unevariable)

7
J'ai fini d'exécuter plus un
7


In [21]:
#Exercice 1
def rechercheElement(tab, elt):
    '''
    entree-sortie tab: tableau d'int
    entree elt: int
    sortie trouve: booléen
    pre-cond: aucune
    post-cond: retourne True si l'élément elt 
               est présent dans le tableau tab
               et False sinon
    '''
    trouve = False
    i = 0
    while i < len(tab) and not trouve:
        if tab[i] == elt:
            trouve = True
        i = i+1
    return trouve

untest = np.array([1, 2, 4, 6, 3, 6, 7, 9])
unautretest = np.array([])

resultat = rechercheElement(untest, 4)
print(resultat)
resultat = rechercheElement(unautretest, 4)
print(resultat)
resultat = rechercheElement(untest, 23)
print(resultat)

True
False
False


In [26]:
def tabEgaux(tab1, tab2):
    verif=True
    if(len(tab1) != len(tab2)):
        verif=False
    i=0
    while i<len(tab1) and verif:
        if(tab1[i] != tab2[i]):
            verif=False
        i = i+1
            
    return verif

t1 = np.array([1, 2, 4, 6, 3, 6, 7, 9])
t2 = np.array([1, 2, 4, 9, 3, 6, 1, 9])
t3 = np.array([1, 2, 4, 6, 3, 6])

print(tabEgaux(t1, t3))

False


In [38]:
#Exercice 3
#Ici, on répond avec deux méthodes pour travailler 
# les appels de fonctions

def prefixe(tabpref,tab):
    '''
    entree-sortie tabpref : tableau d'ints
    entree-sortie tab : tableau d'ints
    pre-cond: len(tabpref) < len(tab)
    post-cond: retourne True si tabpref est 
               un prefixe de tab
    '''
    val=True
    i=0
    while i<len(tabpref) and val:
        if tabpref[i]!=tab[i]:
            val=False
        i+=1
       
    return(val)
            
    

def prefixeGenerique(tab1,tab2):
    '''
    ... idem ...
    post-cond : retrourne True si un des deux 
                tableaux est préfixe de l'autre 
                (mais ne dit pas lequel est préfixe)
    '''
    if len(tab2)<len(tab1):
        val=prefixe(tab2,tab1)
    else:
        val=prefixe(tab1,tab2)
    return(val)

t1 = np.array([1, 2, 4, 6, 3, 6, 7, 9,0])
t2 = np.array([1, 2])
t3 = np.array([1, 4])

print(prefixeGenerique(t1,t2))
print(prefixeGenerique(t2,t1))
print(prefixeGenerique(t1,t3))
print(prefixeGenerique(t3,t1))



True
True
False
False


In [41]:
#Exerice 4 
def mini(tab):
    mini=tab[0]
    for i in range (len(tab)):
        if tab[i]<mini:
            mini=tab[i]
    return(mini)
print(mini(t1))

0


In [43]:
#Exercice 5
def sommetab(tab):
    compte=0
    for i in range(len(tab)):
        compte+=tab[i]
    return compte
    

print(sommetab(t1))

38


In [47]:
#Exercice 6
def moyennetab(tab):
    '''
    pre-cond : tab ne doit pas être vide
    '''
    return sommetab(tab) / len(tab)

print(moyennetab(t1))


4.22222222222


In [54]:
#Exercice 7
def multab(tab,nb):
    i=0
    while i<len(tab):
        tab[i]=nb*tab[i]
        i=i+1
print(t1)
multab(t1,4)
print(t1)

[1024 2048 4096 6144 3072 6144 7168 9216    0]
[ 4096  8192 16384 24576 12288 24576 28672 36864     0]


In [59]:
#Exercice 8 
def decalageADroite(tab):
    i = len(tab)-1
    temp = tab[i]
    while i > 0:
        tab[i] = tab[i-1]
        i=i-1
    tab[0] = temp
print(t1)
decalageADroite(t1)
print(t1)


[36864     0     0  8192 16384 24576 12288 24576 28672]
[28672 36864     0     0  8192 16384 24576 12288 24576]


In [61]:
#Exercice 9
def minDeDeuxTab(t1, t2):
    i = 0
    t3 = np.empty(len(t1))
    while i < len(t1):
        if t1[i] < t2[i]:
            t3[i] = t1[i]
        else:
            t3[i] = t2[i]
        i = i + 1
    return t3

t1 = np.array([1, 2, 4, 5, 7])
t2 = np.array([0, 4, 3, 8, 7])

print(minDeDeuxTab(t1,t2))

[ 0.  2.  3.  5.  7.]
