Nous continuons les tris. Vous devez au moins savoir implémenter :
  * Le tri sélection
  * Le tri insertion
  * Le tri bulle
  
Nous ferons ensuite des exercices sur des tableaux triés. 

In [4]:
# Rappel : nous avons déjà écrit décalage à droite.
# Est-il convenable pour ce que nous voulons faire ici ? 
def decalageADroite(tab):
    i = len(tab)-1
    temp = tab[i]
    while i > 0:
        tab[i] = tab[i-1]
        i=i-1
    tab[0] = temp

In [5]:
import numpy as np

def decADroite(tab,lim1,lim2):
    i= lim2-1
    temp = tab[lim2-1]
    while i > lim1:
        tab[i] = tab[i-1]
        i=i-1
    tab[lim1] = temp
    
t1 = np.array([3,4,1,5,2,8,6])
print("Original", t1)
decalageADroitebis(t1,3,5)
print("Décalage 3, 5", t1)
decalageADroitebis(t1,1,6)
print("Décalage 1, 6", t1)
decalageADroitebis(t1,0,0)
print("Décalage 0, 0", t1)
decalageADroitebis(t1,5,2)
print("Décalage 5, 2", t1)
decalageADroitebis(t1,0,9)
print("Décalage out of bounds", t1)

# observez bien le comportement incohérent (par rapport à ce que l'on attend de la fct)
# de décalage 0, 0 et de décalage 5, 2... 

Original [3 4 1 5 2 8 6]


NameError: name 'decalageADroitebis' is not defined

In [15]:
# Recherche du minimum dans un sous tableau
def rechercheMin(tab, i, j):
    '''
    :entree-sortie tab: un tableau d'ints
    :entrees i, j: les bornes de la recherche (i inclus, j exclus)
    :sorties mini, indmini: entiers
    :pre-cond : i < j, i < len(tab), j <= len(tab)
    :post-cond: retourne le min de tab entre i inclus et j exclus, et indmini, 
                l'indice du minimum retourné 
    '''
    mini = tab[i]
    indmini = i 
    while i < j:
        if tab[i]<mini:
            mini = tab[i]
            indmini = i
        i = i + 1 
    return mini, indmini

t1 = np.array([3,4,1,5,2,8,6,1])
print(rechercheMin(t1,2,7))
print(rechercheMin(t1,3,5))
print(rechercheMin(t1,3,8)) # Comment faire si le min est dans la dernière case ?


(1, 2)
(2, 4)
(1, 7)


In [14]:
def triInsertionRechercheMin(tab):
    j = len(tab)
    for i in range (j):
        mini,indice = rechercheMin(tab, i, j)
        decADroite(tab, i,indice+1)
        
triInsertionRechercheMin(t1)
print(t1)
# A finir pour la prochaine fois 

[1 1 2 3 4 5 6 8]


In [32]:
#Tri par insertion
t1 = np.array([3,4,1,5,2,8,6,1])

def triInsertion(tab):
    for i in range(len(tab)):
        j=i
        while j>0 and tab[j]<tab[j-1]:
                save=tab[j-1]
                tab[j-1]=tab[j]
                tab[j]=save
                j=j-1
triInsertion(t1)
print(t1)

[1 1 2 3 4 5 6 8]


In [33]:
#Tri par Bulle

def triBulle(tab):
    j=1
    for k in range(len(tab)-1):
        
        for i in range(len(tab)-j):
            
            if tab[i]>tab[i+1]:
                save = tab[i]
                tab[i] = tab[i+1]
                tab[i+1] = save
                
        j=j+1

t1 = np.array([3,4,1,5,2,8,6,1])
t2 = np.array([1,2,3,4,5,8,6,1])
triBulle(t1)
triBulle(t2)
print(t1)
print(t2)

[1 1 2 3 4 5 6 8]


**Exercice pour la prochaine fois** : optimiser tri-bulle pour ne plus boucler quand le tableau est trié 

In [34]:
# Tri par indices :
# t1 = np.array([3,1,5,4,1,2])
# Résultat attentu : indices = [1 4 5 0 3 2]
def triParIndices(tab):
    indices = np.empty(len(tab))
    print(indices)
    
t1 = np.array([3,1,5,4,1,2])   
triParIndices(t1)

[  6.92197797e-310   1.87410957e-316   6.92193959e-310   6.92193959e-310
   6.92193959e-310   6.92193959e-310]
