**Exercice 1** Corrigé au tableau

In [2]:
import numpy as np

tableau = np.array([2, 3, 4, 6, 4, 6, 7, 5])
print(tableau)

#Exercice 2
def afficheTabRec(tab, imin, imax):
    if imin==imax:
        print("Fini")
    else:
        print(tab[imin])
        afficheTabRec(tab, imin+1, imax)
    
afficheTabRec(tableau, 2, 5)
    
    

[2 3 4 6 4 6 7 5]
4
6
4
Fini


In [2]:
def test_trié_croissant(tab,imin,imax):
    
    if imin==imax:
        return True
    else:
        if tab[imin]>tab[imin+1]:
            return False
        else:
            return test_trié_croissant(tab,imin+1,imax)
        
print(test_trié_croissant(tableau,0,3))
print(test_trié_croissant(tableau,2,6))

True
False


In [4]:
def compresse_tableau(t):
    k=0
    for i in range(len(t)):
        if t[i]!=0:
            k=k+1
    tind=np.zeros(k)
    tval=np.zeros(k)
    c=0
    for i in range(len(t)):
        if t[i]!=0:
            tind[c]=i
            tval[c]=t[i]
            c=c+1
    return tind, tval

print(compresse_tableau(np.array([0,0,0,0,1,0,0,0,3,0,4])))

(array([  4.,   8.,  10.]), array([ 1.,  3.,  4.]))


In [4]:
tind = np.array([1, 3, 6, 8, 11, 14, 42, 64, 96, 433, 870])
tval = np.array([1.1, 2.2, 6.6, 2.1, 1.1, 13.3, 14.3, 6.0, 9.0, 10.1, 12.11])

In [35]:
def rechercheInd(tab,imin, imax,ind):
    milieu=imin+(imax-imin)//2
    valmilieu=tab[milieu]
    if valmilieu==ind:
        return milieu
    elif imax-imin==1:
        if tab[imin]==ind:
            return imin
        elif tab[imax]==ind:
            return imax
        else :
            return -1
    elif valmilieu>ind:
        imax=milieu
        return rechercheInd(tab,imin,imax,ind)
    else:  #valmilieu<ind
        imin=milieu
        return rechercheInd(tab,imin,imax,ind)
print(rechercheInd(tind,0,len(tind)-1,1))
print(rechercheInd(tind,0,len(tind)-1,3)) 
print(rechercheInd(tind,0,len(tind)-1,6)) 
print(rechercheInd(tind,0,len(tind)-1,8)) 
print(rechercheInd(tind,0,len(tind)-1,11)) 
print(rechercheInd(tind,0,len(tind)-1,14)) 
print(rechercheInd(tind,0,len(tind)-1,42)) 
print(rechercheInd(tind,0,len(tind)-1,64)) 
print(rechercheInd(tind,0,len(tind)-1,96)) 
print(rechercheInd(tind,0,len(tind)-1,433)) 
print(rechercheInd(tind,0,len(tind)-1,870)) 
print(rechercheInd(tind,0,len(tind)-1,65)) 
print(rechercheInd(tind,0,len(tind)-1,66)) 
print(rechercheInd(tind,0,len(tind)-1,2)) 
print(rechercheInd(tind,0,len(tind)-1,13)) 
print(rechercheInd(tind,0,len(tind)-1,17)) 
print(rechercheInd(tind,0,len(tind)-1,912)) 
print(rechercheInd(tind,0,len(tind)-1,0))

def valeur(tval, ind):
    ind2=rechercheInd(tind,0,len(tind)-1,ind)
    if ind2==-1:
        fin=0
    else :
        fin=tval[ind2]
    return fin

valeur(tval, 870)

    

0
1
2
3
4
5
6
7
8
9
10
-1
-1
-1
-1
-1
-1
-1


12.109999999999999

In [22]:
def extraire_valeur (tind, tval, it) :
    if len(tind)==1 :
        return 0
    m=len(tind)//2
    if tind[m]==it :
        return tval[m]
    elif tind[m] > it :
        return(extraire_valeur (tind[:m], tval, it))
    else :
        return(extraire_valeur (tind[m:], tval, it))
    
tind = np.array([1, 3, 6, 8, 11, 14, 42, 64, 96, 433, 870])
tval = np.array([1.1, 2.2, 6.6, 2.1, 1.1, 13.3, 14.3, 6.0, 9.0, 10.1, 12.11])

extraire_valeur(tind, tval, 1)
print(tind)

[  1   3   6   8  11  14  42  64  96 433 870]
